version: "2"
services:
  nacos:
    image: paderlol/nacos:latest
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ./standalone-logs/:/home/nacos/logs
    ports:
    - "8848:8848"
